[dev]
  command = "npm run dev" # Perintah untuk menjalankan Vite (sesuai package.json Anda)
  port = 8888 # Port untuk Netlify Dev
  targetPort = 8080 # Port tempat Vite Anda berjalan
  publish = "dist" # Direktori output build Vite Anda
  framework = "vite"

[build]
  command = "npm run build" # Perintah build Anda
  publish = "dist"

# This is the crucial part for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
